### PR TITLE
feanil/cleanup unused code

### PR DESCRIPTION
**Pull request by feanil**
- docs: Fix the spacing.
- feat!: Remove the other_emails field.
- feat!: Remove the `jira` field.
- feat!: Remove core committer champion pings on PRs.

### CODE REVIEW

**Comment by nedbat** [comment]
I don't see `docs: fix the spacing` in the changes.

**Comment by nedbat** [comment]
Should we update repo-tools-data-schema to get rid of fields we aren't using anymore?

**Comment by nedbat** [comment]
I wonder about `other_emails`: that was because we'd know their non-work email first, and then get edx.org emails, and we didn't want to lose information. Also, it helped figure people out if they were committing from different GitHub accounts.

But we aren't maintaining it anymore, so I guess it should go.

**Review by nedbat — APPROVED** [review]
The changes seem good as far as they go, but what's the plan for repo-tools-data-schema?

**Comment by feanil** [comment]
We'll have to update repo-tools-data-schema in the same way I guess.  I added https://github.com/openedx/repo-tools-data-schema/issues/18 to follow up in that repo.

**Pull request merged**
