### PR TITLE
feat!: remove the survey link

### PR DESCRIPTION
**Pull request by kdmccormick**
Before merging, need to confirm both of these suspicions: 

* Admin access to the Google form (and thus its results) were lost during the Axim/2U decoupling and subsequent edX->2U Google migration.

* There is currently no desire by either Axim or 2U to recreate and manage the survey.

### CODE REVIEW

**Comment by nedbat** [comment]
I'm asking if the form and data can be rescued.

**Comment by nedbat** [comment]
(a test comment)

**Comment by nedbat** [comment]
(this is another test comment.)

**Comment by nedbat** [comment]
2U IT reports that they cannot retrieve the old form or data.

**Comment by kdmccormick** [comment]
Thanks Ned. I'll ask the team today whether we want to make a new form, or just nix it.

**Comment by kdmccormick** [comment]
Good news--we found the data, and it's still coming in, so turning off the survey is less urgent than I had thought.

I wrote up a follow-up task for the future: https://github.com/openedx/openedx-webhooks/issues/259

**Pull request closed without merging**
