### PR TITLE
Remove various easy to fix mentions of repo-tools-data

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Review by Carlos-Muniz — COMMENTED** [review]
There are still a number of mentions of `repo-tools-data` remaining:
- [ ] `openedx_webhooks/lib/edx_repo_tools_data/utils.py`
- [ ] `openedx_webhooks/lib/edx_repo_tools_data/__init__.py`
- [ ] `openedx_webhooks/lib/edx_repo_tools_data/models.py`
- [ ] `Makefile`

This might be another issue, but the requirements still mention the use of `edx/repo-tools-data-schema`, even though that repo is now owned by openedx.

**Comment by feanil** [comment]
@Carlos-Muniz I've got a few more PRs to fix the rest of those that are stacked on top of this one. https://github.com/openedx/openedx-webhooks/pulls/feanil  so we'll get to some of that.  As for repo-tools-data-schema, yea that's a whole another can of worms that I'm not going to be addressing with my fixes.

**Comment by Carlos-Muniz** [comment]
@feanil
Is there a reason why you didn't tackle the rest of the mentions of `repo-tools-data` in this PR and are instead putting it in other PRs? I think it's all the same type of work and should be in the same PR.

**Comment by feanil** [comment]
Yes, I figured the PRs would be smaller and easier to review in picees and some of the work required further changes and testing than other work.

**Review by Carlos-Muniz — APPROVED** [review]
Thanks for addressing my comments. I agree that easy to review PRs makes quicker progress. And as long as the files mentioned are changed in other PRs, I think the work here is good enough to be merged.

**Pull request merged**
